image:
  registry: docker.io

postgresImageRegistry: docker.io
imagePullSecrets: [ ]

server:
  port: 7002
  policyRepoUrl: "https://github.com/permitio/opal-example-policy-repo"
  policyRepoSshKey: null
  policyRepoClonePath: null
  policyRepoMainBranch: null
  pollingInterval: 30
  dataConfigSources:
    # Option #1 - No data sources
    config:
      entries: []

    # Option #2 - Dynamically get data sources
    # external_source_url: "https://your-api.com/path/to/api/endpoint"

    # Option #3 - Example static data sources (endpoint is empty by default)
    # config:  
    #   entries:
    #   - url: http://opal-server:7002/policy-data
    #     topics: ["policy_data"]
    #     dst_path: "/static"

  broadcastUri: null
  broadcastPgsql: true
  uvicornWorkers: 4
  replicas: 1
  extraEnv:
    "CUSTOM_ENV_VAR": "VALUE"

client:
  port: 7000
  opaPort: 8181
  replicas: 1
  extraEnv:
    "CUSTOM_ENV_VAR": "VALUE"
