imageRegistry: docker.io
postgresImageRegistry: docker.io
imagePullSecrets: [ ]

server:
  port: 7002
  policyRepoUrl: "https://github.com/permitio/opal-example-policy-repo"
  policyRepoSshKey: null
  policyRepoClonePath: null
  policyRepoMainBranch: null
  pollingInterval: 30
  dataConfigSources:
    external_source_url: "https://your-api.com/path/to/api/endpoint"
  broadcastUri: null
  broadcastPgsql: true
  uvicornWorkers: 4
  replicas: 1
  extraEnv:
    "CUSTOM_ENV_VAR": "VALUE"

client:
  port: 7000
  opaPort: 8181
  replicas: 1
  extraEnv:
    "CUSTOM_ENV_VAR": "VALUE"

